export type SalonService = {
  name: string;
  price: number | "Price on consultation";
};

export type ServiceGroup = {
  id: string;
  title: string;
  description: string;
  services: SalonService[];
};

export const serviceGroups: ServiceGroup[] = [
  {
    id: "cuts-styling",
    title: "Haircuts & styling",
    description: "Cuts, washes and styling, with prices based on hair length where shown.",
    services: [
      { name: "Cut & style", price: 350 },
      { name: "Kid’s haircut", price: 250 },
      { name: "Fringe cut", price: 150 },
      { name: "Wash & plain dryer", price: 150 },
      { name: "Keratin hair wash", price: 250 },
      { name: "Wash & blow dry — up to neck", price: 250 },
      { name: "Wash & blow dry — up to shoulder", price: 300 },
      { name: "Wash & blow dry — waist & below", price: 350 },
      { name: "Wash & ironing — up to neck", price: 350 },
      { name: "Wash & ironing — up to shoulder", price: 500 },
      { name: "Wash & ironing — waist & below", price: 600 },
      { name: "Tongs — up to neck", price: 400 },
      { name: "Tongs — up to shoulder", price: 500 },
      { name: "Tongs — waist & below", price: 600 },
    ],
  },
  {
    id: "hair-care",
    title: "Hair spa & treatments",
    description: "Hair spa, scalp care, smoothening, rebonding and straightening services.",
    services: [
      { name: "Basic hair spa — up to neck", price: 600 },
      { name: "Basic hair spa — up to shoulder", price: 800 },
      { name: "Basic hair spa — waist & below", price: 1100 },
      { name: "Dandruff treatment", price: 1000 },
      { name: "Hair fall treatment", price: 1200 },
      { name: "Smartbond treatment", price: 1500 },
      { name: "Protein hair spa — up to neck", price: 1000 },
      { name: "Protein hair spa — up to shoulder", price: 1200 },
      { name: "Protein hair spa — waist & below", price: 1500 },
      { name: "Premium hair spa — up to neck", price: 2000 },
      { name: "Premium hair spa — up to shoulder", price: 2200 },
      { name: "Premium hair spa — waist & below", price: 2500 },
      { name: "Smoothening — up to neck", price: 3000 },
      { name: "Smoothening — up to shoulder", price: 4500 },
      { name: "Smoothening — waist & below", price: 6500 },
      { name: "Rebonding — up to neck", price: 5500 },
      { name: "Rebonding — up to shoulder", price: 6500 },
      { name: "Rebonding — waist & below", price: 7500 },
      { name: "Kera Strait — up to neck", price: 6000 },
      { name: "Kera Strait — up to shoulder", price: 8000 },
      { name: "Kera Strait — waist & below", price: 10000 },
    ],
  },
  {
    id: "hair-colour",
    title: "Hair colour & highlights",
    description: "Root touch-ups, global colour and highlights.",
    services: [
      { name: "Root touch-up — 1 inch", price: 600 },
      { name: "Root touch-up — 2 inch", price: 900 },
      { name: "Organic root touch-up — 1 inch", price: 800 },
      { name: "Organic root touch-up — 2 inch", price: 1000 },
      { name: "Global colouring — up to neck", price: 2000 },
      { name: "Global colouring — up to shoulder", price: 3000 },
      { name: "Global colouring — waist & below", price: 4000 },
      { name: "Global highlights — up to neck", price: 2500 },
      { name: "Global highlights — up to shoulder", price: 3500 },
      { name: "Global highlights — waist & below", price: 5000 },
      { name: "Customised highlights", price: "Price on consultation" },
    ],
  },
  {
    id: "cleanups-facials",
    title: "Cleanups & facials",
    description: "Skin cleanups, facials and optional masks.",
    services: [
      { name: "Basic cleanup", price: 400 },
      { name: "Fruit cleanup", price: 500 },
      { name: "Hydra cleanup", price: 600 },
      { name: "Purifying cleanup", price: 600 },
      { name: "White brightening cleanup", price: 900 },
      { name: "Swete cleanup", price: 900 },
      { name: "Organic cleanup", price: 1200 },
      { name: "Basic facial", price: 600 },
      { name: "Instant Glow (Lotus) facial", price: 1200 },
      { name: "Bye Bye Tan Facial (Adanse)", price: 1000 },
      { name: "Sensi Balance facial", price: 1200 },
      { name: "Fruit facial (basic)", price: 800 },
      { name: "Complexion enhancement facial", price: 1500 },
      { name: "O+ facial", price: 1500 },
      { name: "Organic facial", price: 2000 },
      { name: "Goji brightening facial", price: 2500 },
      { name: "O+ Sublime facial", price: 3000 },
      { name: "Pampering facial", price: 4000 },
      { name: "Glow mask", price: 350 },
      { name: "Fruit mask", price: 500 },
      { name: "Skin firming mask", price: 800 },
      { name: "Green tea mask", price: 800 },
      { name: "Rubber mask", price: 800 },
      { name: "Collagen mask", price: 1200 },
    ],
  },
  {
    id: "bleach-detan",
    title: "Bleach & detan",
    description: "Targeted bleach and detan services for face and body areas.",
    services: [
      { name: "Face bleach", price: 200 },
      { name: "Face detan", price: 300 },
      { name: "Face & neck bleach", price: 350 },
      { name: "Face & neck detan", price: 400 },
      { name: "Face, neck & blouse line bleach", price: 400 },
      { name: "Face, neck & blouse line detan", price: 500 },
      { name: "Underarms bleach", price: 80 },
      { name: "Underarms detan", price: 100 },
      { name: "Feet bleach", price: 250 },
      { name: "Feet detan", price: 300 },
      { name: "Full arms bleach", price: 350 },
      { name: "Full arms detan", price: 500 },
      { name: "Half arms bleach", price: 300 },
      { name: "Half arms detan", price: 400 },
      { name: "Full legs bleach", price: 600 },
      { name: "Full legs detan", price: 800 },
      { name: "Half legs bleach", price: 400 },
      { name: "Half legs detan", price: 500 },
      { name: "Midriff bleach", price: 350 },
      { name: "Midriff detan", price: 400 },
      { name: "Full back bleach", price: 450 },
      { name: "Full back detan", price: 500 },
      { name: "Half back bleach", price: 250 },
      { name: "Half back detan", price: 300 },
      { name: "Full front bleach", price: 450 },
      { name: "Full front detan", price: 500 },
      { name: "Half front bleach", price: 300 },
      { name: "Half front detan", price: 400 },
      { name: "Full body bleach", price: 1800 },
      { name: "Full body detan", price: 2200 },
    ],
  },
  {
    id: "waxing",
    title: "Waxing",
    description: "Regular and flavoured waxing services.",
    services: [
      { name: "Underarms waxing", price: 50 },
      { name: "Full arms waxing", price: 150 },
      { name: "Half legs waxing", price: 250 },
      { name: "Full legs waxing", price: 350 },
      { name: "Midriff waxing", price: 250 },
      { name: "Full back / front waxing", price: 350 },
      { name: "Full front waxing", price: 350 },
      { name: "Full body waxing", price: 1350 },
      { name: "Bikini line waxing", price: 1000 },
      { name: "Face flavoured waxing", price: 350 },
      { name: "Chin flavoured waxing", price: 50 },
      { name: "Upper lip flavoured waxing", price: 50 },
      { name: "Eyebrow flavoured waxing", price: 50 },
      { name: "Underarms flavoured waxing", price: 80 },
      { name: "Full arms flavoured waxing", price: 350 },
      { name: "Half legs flavoured waxing", price: 300 },
      { name: "Full legs flavoured waxing", price: 500 },
      { name: "Midriff flavoured waxing", price: 350 },
      { name: "Full back flavoured waxing", price: 400 },
      { name: "Full front flavoured waxing", price: 400 },
      { name: "Full body flavoured waxing", price: 2000 },
      { name: "Bikini line flavoured waxing", price: 1500 },
    ],
  },
  {
    id: "nails",
    title: "Nails, manicure & pedicure",
    description: "Polish, nail care, manicures, pedicures and nail extensions.",
    services: [
      { name: "Change of polish", price: 60 },
      { name: "Feet polish", price: 100 },
      { name: "Cut & polish", price: 150 },
      { name: "Basic pedicure", price: 450 },
      { name: "Basic manicure", price: 350 },
      { name: "Aroma pedicure", price: 550 },
      { name: "Aroma manicure", price: 450 },
      { name: "Luxury pedicure", price: 800 },
      { name: "Luxury manicure", price: 600 },
      { name: "Relaxing foot spa with machine", price: 1200 },
      { name: "Feet massage — 20 minutes", price: 250 },
      { name: "Feet massage — 30 minutes", price: 350 },
      { name: "Gel nail paint", price: 600 },
      { name: "Nail extension", price: 3000 },
      { name: "Body exfoliation", price: 800 },
      { name: "Back exfoliation", price: 350 },
      { name: "Hand exfoliation", price: 250 },
    ],
  },
  {
    id: "massage-exfoliation",
    title: "Massage & exfoliation",
    description: "Body-area exfoliation and massage services.",
    services: [
      { name: "Half hand exfoliation", price: 300 },
      { name: "Full leg exfoliation", price: 450 },
      { name: "Half legs exfoliation", price: 300 },
      { name: "Body massage", price: 1500 },
      { name: "Back massage", price: 400 },
      { name: "Hand massage", price: 250 },
      { name: "Feet massage", price: 250 },
    ],
  },
];

export const allServices = serviceGroups.flatMap((group) => group.services);

export function formatPrice(price: SalonService["price"]) {
  return typeof price === "number"
    ? new Intl.NumberFormat("en-IN", {
        style: "currency",
        currency: "INR",
        maximumFractionDigits: 0,
      }).format(price)
    : price;
}
